// This file is auto-generated by scripts/generate-recipes-index.mjs.
// Do not edit by hand. Run `pnpm generate:recipes` to regenerate.
import type { RecipeModuleLoader } from "./types";

export const reactRecipeLoaders: Record<string, RecipeModuleLoader> = {
	"air-quality": () =>
		import("../../app/(app)/recipes/screens/air-quality/air-quality"),
	album: () => import("../../app/(app)/recipes/screens/album/album"),
	"bitcoin-price": () =>
		import("../../app/(app)/recipes/screens/bitcoin-price/bitcoin-price"),
	"bitmap-patterns": () =>
		import("../../app/(app)/recipes/screens/bitmap-patterns/bitmap-patterns"),
	"botanical-plate": () =>
		import("../../app/(app)/recipes/screens/botanical-plate/botanical-plate"),
	calendar: () => import("../../app/(app)/recipes/screens/calendar/calendar"),
	"daily-print": () =>
		import("../../app/(app)/recipes/screens/daily-print/daily-print"),
	"device-calibration": () =>
		import(
			"../../app/(app)/recipes/screens/device-calibration/device-calibration"
		),
	"github-contributions": () =>
		import(
			"../../app/(app)/recipes/screens/github-contributions/github-contributions"
		),
	"hacker-news": () =>
		import("../../app/(app)/recipes/screens/hacker-news/hacker-news"),
	"local-news": () =>
		import("../../app/(app)/recipes/screens/local-news/local-news"),
	"month-calendar": () =>
		import("../../app/(app)/recipes/screens/month-calendar/month-calendar"),
	"moon-almanac": () =>
		import("../../app/(app)/recipes/screens/moon-almanac/moon-almanac"),
	"not-found": () =>
		import("../../app/(app)/recipes/screens/not-found/not-found"),
	"responsive-example": () =>
		import(
			"../../app/(app)/recipes/screens/responsive-example/responsive-example"
		),
	"simple-text": () =>
		import("../../app/(app)/recipes/screens/simple-text/simple-text"),
	"sunrise-sunset": () =>
		import("../../app/(app)/recipes/screens/sunrise-sunset/sunrise-sunset"),
	weather: () => import("../../app/(app)/recipes/screens/weather/weather"),
	"whos-overhead": () =>
		import("../../app/(app)/recipes/screens/whos-overhead/whos-overhead"),
	wikipedia: () =>
		import("../../app/(app)/recipes/screens/wikipedia/wikipedia"),
	"year-progress": () =>
		import("../../app/(app)/recipes/screens/year-progress/year-progress"),
};

export const reactRecipeSlugs = [
	"air-quality",
	"album",
	"bitcoin-price",
	"bitmap-patterns",
	"botanical-plate",
	"calendar",
	"daily-print",
	"device-calibration",
	"github-contributions",
	"hacker-news",
	"local-news",
	"month-calendar",
	"moon-almanac",
	"not-found",
	"responsive-example",
	"simple-text",
	"sunrise-sunset",
	"weather",
	"whos-overhead",
	"wikipedia",
	"year-progress",
] as const;

export type ReactRecipeSlug = (typeof reactRecipeSlugs)[number];
